### ISSUE TITLE
Error during execution process

### ISSUE THREAD

**Issue by overlineink** [mickdec/Wormler#3]
![x](https://user-images.githubusercontent.com/24974840/57988756-b9edfa00-7a89-11e9-91f7-310ed601b512.jpg)

**Comment by mickdec** [comment]
An ETIMEOUT mean your request timedout. You didnt get a response for that request and node throw an error. Try to reduce the time between each requests with the `-s` argument wich increase requests delay. It could be because you'r internet connection is to slow or the server can't be contacted (like a ENOTFOUND).If you prefer it could be referenced as a error 408 
https://developer.mozilla.org/fr/docs/Web/HTTP/Status/408
